import type { Metadata } from 'next'
import { Inter, Space_Grotesk } from 'next/font/google'

// Yanone_Kaffeesatz | Space_Grotesk

import './globals.css'

const sans = Space_Grotesk({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "FlickrFolio | A photo gallery by Free O'Toole",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${sans.className} font-light leading-loose`}>
        {children}
      </body>
    </html>
  )
}
